/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArticleCreate { 
    mod_number: string;
    price: number;
    unit_id: number;
    name_de: string;
    name_it: string;
    description_de: string;
    description_it: string;
    category_ids: Array<number>;
    vat_id: number;
}

