/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Vat } from './vat';
import { Text } from './text';
import { Unit } from './unit';
import { Lock } from './lock';


export interface Article { 
    mod_number: string;
    price: number;
    id: number;
    lock: Lock;
    unit: Unit;
    name: Text;
    description: Text;
    categories: Array<Category>;
    vat: Vat;
    deleted: boolean;
}

