/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Lock } from './lock';


export interface Calendar { 
    title: string;
    description: string;
    start_time: string;
    end_time: string;
    id: number;
    timestamp: string;
    user: User;
    lock: Lock;
}

