/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobTypeType } from './jobTypeType';
import { OutgoingInvoice } from './outgoingInvoice';
import { Address } from './address';
import { JobStatusType } from './jobStatusType';
import { Offer } from './offer';
import { Orderable } from './orderable';
import { Client } from './client';
import { Lock } from './lock';


export interface Job { 
    description: string;
    id: number;
    lock: Lock;
    orderable: Orderable;
    timestamp: string;
    year: number;
    code: string;
    offers?: Array<Offer>;
    outgoing_invoices?: Array<OutgoingInvoice>;
    client: Client;
    address: Address;
    archive: boolean;
    status: JobStatusType;
    type: JobTypeType;
    path: string;
}

