/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobTypeType } from './jobTypeType';
import { AddressCreate } from './addressCreate';


export interface JobCreate { 
    description: string;
    name: string;
    client_id: number;
    address: AddressCreate;
    type: JobTypeType;
    path: string;
}

