/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type JobStatusType = 'CREATED' | 'ACCEPTED' | 'FINISHED' | 'OTHER';

export const JobStatusType = {
    Created: 'CREATED' as JobStatusType,
    Accepted: 'ACCEPTED' as JobStatusType,
    Finished: 'FINISHED' as JobStatusType,
    Other: 'OTHER' as JobStatusType
};

