/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderedArticleCreate } from './orderedArticleCreate';


export interface OfferCreate { 
    date: string;
    in_price_included: string;
    in_price_excluded: string;
    payment: string;
    delivery: string;
    job_id: number;
    ordered_articles: Array<OrderedArticleCreate>;
}

