/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { Unit } from './unit';


export interface OrderedArticle { 
    amount: number;
    discount: number;
    vat: number;
    custom_description: string;
    alternative: boolean;
    id: number;
    ordered_unit: Unit;
    article: Article;
}

