/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Orderable } from './orderable';
import { OrderStatusType } from './orderStatusType';
import { OrderedArticle } from './orderedArticle';
import { Lock } from './lock';


export interface Order { 
    description: string;
    id: number;
    lock: Lock;
    order_from: Orderable;
    order_to: Orderable;
    create_date: string;
    delivery_date?: string;
    pdf?: string;
    articles: Array<OrderedArticle>;
    status: OrderStatusType;
}

