/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderedArticleCreate { 
    amount: number;
    discount: number;
    vat: number;
    custom_description: string;
    alternative: boolean;
    ordered_unit_id: number;
    article_id: number;
}

