/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Language } from './language';
import { Article } from './article';
import { Orderable } from './orderable';
import { Lock } from './lock';


export interface Supplier { 
    mail1: string;
    mail2: string;
    tel1: string;
    tel2: string;
    id: number;
    lock: Lock;
    orderable: Orderable;
    address: Address;
    language: Language;
    articles?: Array<Article>;
}

