/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressCreate } from './addressCreate';


export interface SupplierCreate { 
    mail1: string;
    mail2: string;
    tel1: string;
    tel2: string;
    name: string;
    address: AddressCreate;
    language_code: string;
}

